project: cloud-native-sample
source:
  repoURL: https://github.com/maocypher/cloud-native-argo-sample.git
  path: kafka
  targetRevision: HEAD
  directory:
    recurse: true
    jsonnet:
      tlas:
        - name: ''
          value: ''
destination:
  server: https://kubernetes.default.svc
  namespace: kafka-2025-11
syncPolicy:
  automated:
    selfHeal: true
    enabled: true
  retry:
    limit: 2
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m0s

