apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
spec:
  destination:
    namespace: redis
    server: https://kubernetes.default.svc
  source:
    path: redis
    repoURL: https://github.com/maocypher/cloud-native-argo-sample.git
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin
  sources: []
  project: cloud-native-sample
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
