apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    # Your Git repo containing values
    repoURL: https://github.com/maocypher/cloud-native-argo-sample
    targetRevision: HEAD
    path: vault
    
    # External Helm chart configuration
    helm:
      # Reference to external Helm chart
      chart: vault
      version: "0.30.1"
      repo: https://helm.releases.hashicorp.com
      
      # Your custom values files
      valueFiles:
        - override-values.yaml
          
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true