apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: redis
  annotations:
    avp.kubernetes.io/path: "secret/data/redis"
    avp.kubernetes.io/secret-version: "1"
type: Opaque
data:
  password: <password>